### ISSUE TITLE
Quiz mit / im Namen kann nicht gespeichert werden

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2022-10#19]
Es wird ein Verzeichnis gesucht, das so heißt wie der Teil vor dem /
```none
E/flutter ( 5991): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: 
Cannot open file, path = '/data/user/0/de.mitutoyo.learnhub/app_flutter/questionStacks/no/no.json' 
(OS Error: No such file or directory, errno = 2)
E/flutter ( 5991): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 5991): <asynchronous suspension>
E/flutter ( 5991): #1      DataHelper.save (package:learnhub/DataHelper/DataHelper.dart:100:7)
E/flutter ( 5991): <asynchronous suspension>
```

**Comment by thomasw-mitutoyo-ctl** [comment]
Mit einem Quiz namens ../x kann man auf den übergeordneten Ordner zugreifen.

**Comment by thomasw-mitutoyo-ctl** [comment]
Relevant for fix: https://stackoverflow.com/questions/2679699/what-characters-allowed-in-file-names-on-android

**Comment by thomasw-mitutoyo-ctl** [comment]
Jetzt sind die Schrägstriche im Namen des Stapels weg und durch Unterstriche ersetzt.
